<?php

namespace IceTea\IceDOM;

use Stringable;

use function ob_get_clean;
use function ob_start;

/**
 * A specialized Node that captures and returns raw output from its children.
 *
 * The EchoNode class extends the base Node functionality by using PHP's output
 * buffering to capture any direct output (echo, print, etc.) generated by its
 * children. This is particularly useful when working with legacy code or
 * components that output content directly rather than returning it as strings.
 *
 * Unlike the base Node class which converts children to strings and concatenates
 * them, EchoNode evaluates each child using tryEvalClosure() within an output
 * buffer, capturing any direct output. This allows the node to handle:
 * - Closures that use echo/print statements
 * - Legacy functions that output directly
 * - Components that mix return values with direct output
 *
 * The captured output is returned as-is without any HTML escaping, making it
 * suitable for raw HTML output or when the content has already been properly
 * escaped by the child components.
 *
 * Example usage:
 * ```php
 * $echoNode = new EchoNode([
 *     function() {
 *         echo '<div>Hello World</div>';
 *         return ' - returned value';
 *     }
 * ]);
 *
 * // Output: '<div>Hello World</div> - returned value'
 * echo $echoNode;
 * ```
 */
class EchoNode extends Node
{
    /**
     * Converts the node to its string representation by capturing output from children.
     *
     * This method uses PHP's output buffering to capture any direct output generated
     * by evaluating the node's children. Each child is processed through tryEvalClosure()
     * which handles closures by executing them with the current node as context.
     *
     * The method:
     * 1. Starts output buffering with ob_start()
     * 2. Iterates through all children, evaluating each via tryEvalClosure()
     * 3. Captures and returns the buffered content
     * 4. Returns an empty string if no output was captured
     *
     * Unlike the parent Node class, this method does not perform HTML escaping
     * on the captured output, making it suitable for raw HTML content.
     *
     * @return string The captured output from all children, or empty string if no output
     */
    protected function childrenToString(): string
    {
        ob_start();
        foreach ($this->children as $child) {
            $evaluatedChild = $this->tryEvalClosure($child);

            if ($evaluatedChild instanceof Node) {
                echo $evaluatedChild->__toString();
            } elseif ($evaluatedChild instanceof SafeString) {
                echo $evaluatedChild->__toString();
            } elseif (is_string($evaluatedChild)) {
                echo $evaluatedChild;
            } elseif (is_int($evaluatedChild) || is_float($evaluatedChild)) {
                echo $evaluatedChild;
            } elseif ($evaluatedChild instanceof Stringable) {
                echo $evaluatedChild->__toString();
            }
        }
        $raw = ob_get_clean() ?: '';

        return $raw;
    }
}
