<?php

use IceTea\IceDOM\HtmlNode;

require_once __DIR__.'/Node.php';
require_once __DIR__.'/HtmlNode.php';

$dashToCamelCase = function ($str) {
    $parts = explode('-', $str);

    return implode('', array_map(
        fn ($idx, $c) => $idx > 0 ? ucfirst(strtolower($c)) : strtolower($c),
        array_keys($parts),
        array_values($parts)
    ));
};
// htmlelement properties
$htmlElementProperties = [
    'accept',
    'accept-charset',
    'accesskey',
    'action',
    'align',
    'alt',
    'async',
    'autocapitalize',
    'autocomplete',
    'autofocus',
    'autoplay',
    'bgcolor',
    'border',
    'buffered',
    'capture',
    'challenge',
    'charset',
    'checked',
    'cite',
    'class',
    'code',
    'codebase',
    'color',
    'cols',
    'colspan',
    'content',
    'contenteditable',
    'contextmenu',
    'controls',
    'coords',
    'crossorigin',
    'csp',
    'data',
    'datetime',
    'decoding',
    'default',
    'defer',
    'dir',
    'dirname',
    'disabled',
    'download',
    'draggable',
    'enctype',
    'enterkeyhint',
    'for',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'headers',
    'height',
    'hidden',
    'high',
    'href',
    'hreflang',
    'http-equiv',
    'icon',
    // "id",
    'importance',
    'integrity',
    'intrinsicsize',
    'inputmode',
    'ismap',
    'itemprop',
    'keytype',
    'kind',
    'label',
    'lang',
    'language',
    'loading',
    'list',
    'loop',
    'low',
    'manifest',
    'max',
    'maxlength',
    'minlength',
    'media',
    'method',
    'min',
    'multiple',
    'muted',
    'name',
    'novalidate',
    'open',
    'optimum',
    'pattern',
    'ping',
    'placeholder',
    'poster',
    'preload',
    'radiogroup',
    'readonly',
    'referrerpolicy',
    'rel',
    'required',
    'reversed',
    'rows',
    'rowspan',
    'sandbox',
    'scope',
    'scoped',
    'selected',
    'shape',
    'size',
    'sizes',
    'slot',
    'span',
    'spellcheck',
    'src',
    'srcdoc',
    'srclang',
    'srcset',
    'start',
    'step',
    'style',
    'summary',
    'tabindex',
    'target',
    'title',
    'translate',
    'type',
    'usemap',
    'value',
    'width',
    'wrap',
];

$propStr = implode("\n", array_map(function ($tag) use ($dashToCamelCase) {
    return sprintf(<<<EOT
    \tpublic function %s(\$value%s) : static { \$this->attrs['%s'] = \$value; return \$this; }
    EOT, $dashToCamelCase($tag), in_array($tag, HtmlNode::BOOLEAN_ATTRS) ? ' = true' : '', $tag);
}, $htmlElementProperties));

$old = file_get_contents(__DIR__.'/HtmlNode.php');
$parts = explode('// GENERATED', $old);
$parts[1] = "\n\t".trim($propStr)."\n\t";
file_put_contents(__DIR__.'/HtmlNode.php', implode('// GENERATED', $parts));
